### ISSUE TITLE
Simplify the Authenticate class and /login/index.php

### ISSUE THREAD

**Issue by invisal** [devdil/www.gnooble.org#10]
SQL query shouldn't belong near the HTML code. It will become too messy soon. In your `login/index.php`, the code is too messy. Ideally, we can reduce it to something like this

    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
         if (Authenticate::login($_POST['useremail'], $_POST['password'])) {
              // do the redirect, successfully login
         } else {
              // incorrect email or passsword
         }
    }

And put all the hard work to the Authenticate class. It makes thing easier to read this way.

**Comment by devdil** [comment]
Will improve the authentication class
