### ISSUE TITLE
Fix html issues in /student/editor.php.

### ISSUE THREAD

**Issue by devdil** [devdil/www.gnooble.org#12]
* Pull the code
* Fix the design issues preserving the php code.

**Comment by maxxon15** [comment]
I'm getting huge errors in the login page itself. Can't login on my end.
Apparently you have made a lot of changes with the filenames.... but forgot to refer to the proper ones from other files?

Are these errors showing up your end or am I missing something here?

![screencapture-gnooble-dev-login](https://cloud.githubusercontent.com/assets/1046598/5887764/de68edf4-a397-11e4-8ec3-10f71cc602df.png)
