### ISSUE TITLE
Redirection problem: Cannot redirect after login or registration

### ISSUE THREAD

**Issue by maxxon15** [devdil/www.gnooble.org#2]
As for the registration problem, it seems the new users aren't getting created at all.

While on logging in, it just redirects to the same page. Doesn't redirect to the student/admin area like its supposed to.

I'm pretty sure, https://github.com/devdil/www.gnooble.org/commit/27593e54a30be5a664865e2628d186c5557e1bd9#diff-46a066dbb3a9ae03792fe0de73c23677R71 commit isn't causing the problem though.

**Comment by devdil** [comment]
It is...I added the name value pairs for each ..and you pushed your code to the main branch...which did not contain my updates.So Please pull and then push your code,otherwise it will be a tough time

**Comment by devdil** [comment]
The issue is resolved if the action method in the page is modified to action="/register/" or action="/login/"..The dirname function was causing the trouble

**Comment by maxxon15** [comment]
@devdil Hm... I see. Btw, always do a pull before push to Github. else you'll end up with merge conflicts.
