### ISSUE TITLE
new issue with the login page still persists.

### ISSUE THREAD

**Issue by devdil** [devdil/www.gnooble.org#3]
![issue2](https://cloud.githubusercontent.com/assets/5098875/5658297/7024f758-9725-11e4-9712-4aebbafabef2.jpg)

**Comment by maxxon15** [comment]
Are you sure? Pull from the repo and try again?
![screen shot 2015-01-08 at 5 15 40 pm](https://cloud.githubusercontent.com/assets/1046598/5662032/18f76d04-96e8-11e4-9dda-d2404a0b0188.png)

**Comment by devdil** [comment]
lclose the issue..its working now..pulled and checked...lets now issues
with the student section

**Comment by maxxon15** [comment]
Fixed https://github.com/devdil/www.gnooble.org/commit/bf92b32b1cfff8f094f1586e992e60e22d0078dc
